# **AI TECH INSTITUTE** · *Intermediate AI & Data Science*
### Week 3 - Notebook 01: SQL Fundamentals for Absolute Beginners
**Instructor:** Amir Charkhi |  **Goal:** SQL Fundamentals

> Format: theory → implementation → best practices → real-world application.

## Your First Steps into the World of Databases

**Learning Objectives:**
- Understand what SQL is and why it's essential for data science
- Learn how databases differ from CSV/Excel files
- Convert pandas DataFrames to SQL databases
- Write your first SQL queries
- Read from and write to databases using Python
- Master the essential SQL commands

**Prerequisites:** Basic Python and pandas knowledge

## 🤔 Why Should I Care About SQL?

Imagine you work at Netflix:
- **500 million** users
- **50 billion** viewing events per month
- **10 TB** of data generated daily

Can you load this into pandas? **NO!** Your computer would explode! 💥

This is where SQL comes in:
- Process **billions** of rows without loading them into memory
- Query data that's **100x larger** than your RAM
- Share data across **teams** without sending files
- Get results in **seconds** instead of hours

**Bottom line:** If you want a data job, you NEED SQL. It's used by:
- 🏢 **Every** tech company (Google, Meta, Amazon, Netflix)
- 🏦 **Every** bank and financial institution
- 🏥 **Every** healthcare organization
- 🛍️ **Every** retail company

## 📚 Part 0: Essential Libraries and Tools

Let's understand the Python libraries for working with databases.

In [1]:
# Essential imports for SQL in Python
import pandas as pd
import numpy as np
import sqlite3  # Built-in SQL database
from sqlalchemy import create_engine  # Advanced database toolkit
import warnings
warnings.filterwarnings('ignore')

# For visualization
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

print("📚 Library Guide:")
print("")
print("1. sqlite3: Built into Python, perfect for learning")
print("   - Serverless database (just a file)")
print("   - Great for prototypes and small projects")
print("")
print("2. pandas: Your bridge between Python and SQL")
print("   - pd.read_sql(): Read SQL query results into DataFrame")
print("   - df.to_sql(): Save DataFrame to database")
print("")
print("3. sqlalchemy: Professional database toolkit")
print("   - Works with any database (PostgreSQL, MySQL, etc.)")
print("   - Connection pooling and advanced features")
print("")
print("✅ All libraries loaded and ready!")

📚 Library Guide:

1. sqlite3: Built into Python, perfect for learning
   - Serverless database (just a file)
   - Great for prototypes and small projects

2. pandas: Your bridge between Python and SQL
   - pd.read_sql(): Read SQL query results into DataFrame
   - df.to_sql(): Save DataFrame to database

3. sqlalchemy: Professional database toolkit
   - Works with any database (PostgreSQL, MySQL, etc.)
   - Connection pooling and advanced features

✅ All libraries loaded and ready!

---

## 🗄️ Part 1: What Exactly is SQL?

**SQL** = Structured Query Language (pronounced "sequel" or "S-Q-L")

Think of it as **English for talking to databases**.

In [2]:
# Let's see SQL in action with a simple example
print("🎯 SQL vs Pandas Comparison\n")
print("Task: Get all customers from USA\n")

print("PANDAS way:")
print("  df[df['country'] == 'USA']")
print("")
print("SQL way:")
print("  SELECT * FROM customers WHERE country = 'USA'")
print("")
print("💡 SQL reads almost like English!")
print("")
print("="*50)
print("")
print("🔑 Key Concepts:")
print("")
print("1. DATABASE: A container for tables (like an Excel file)")
print("2. TABLE: Structured data (like an Excel sheet or pandas DataFrame)")
print("3. ROW: A single record (like a row in pandas)")
print("4. COLUMN: A field/attribute (like a column in pandas)")
print("5. QUERY: A question you ask the database")

🎯 SQL vs Pandas Comparison

Task: Get all customers from USA

PANDAS way:
  df[df['country'] == 'USA']

SQL way:
  SELECT * FROM customers WHERE country = 'USA'

💡 SQL reads almost like English!

==================================================

🔑 Key Concepts:

1. DATABASE: A container for tables (like an Excel file)
2. TABLE: Structured data (like an Excel sheet or pandas DataFrame)
3. ROW: A single record (like a row in pandas)
4. COLUMN: A field/attribute (like a column in pandas)
5. QUERY: A question you ask the database

### 1.1 CSV/Excel vs Database - What's the Difference?

In [62]:
# Create a comparison table
comparison = pd.DataFrame({
    'Aspect': ['Size Limit', 'Speed', 'Multiple Users', 'Data Integrity', 
               'Relationships', 'Querying', 'Storage'],
    'CSV/Excel': ['~1M rows', 'Slow for large files', 'File conflicts', 
                  'No validation', 'Manual', 'Load everything', 'Entire file in memory'],
    'SQL Database': ['Billions of rows', 'Fast at any size', 'Concurrent access', 
                     'Data types enforced', 'Foreign keys', 'Get only what you need', 'On disk, query in chunks']
})

print("📊 CSV/Excel vs SQL Database:\n")
print(comparison.to_string(index=False))
print("\n💡 Rule of thumb:")
print("  - < 10,000 rows: CSV is fine")
print("  - 10,000 - 1M rows: Consider SQL")
print("  - > 1M rows: Definitely use SQL")

📊 CSV/Excel vs SQL Database:

        Aspect             CSV/Excel             SQL Database
    Size Limit              ~1M rows         Billions of rows
         Speed  Slow for large files         Fast at any size
Multiple Users        File conflicts        Concurrent access
Data Integrity         No validation      Data types enforced
 Relationships                Manual             Foreign keys
      Querying       Load everything   Get only what you need
       Storage Entire file in memory On disk, query in chunks

💡 Rule of thumb:
  - < 10,000 rows: CSV is fine
  - 10,000 - 1M rows: Consider SQL
  - > 1M rows: Definitely use SQL

---

## 🏗️ Part 2: Creating Your First Database

Let's create a database from scratch and understand how it works!

### 2.1 Creating a Database Connection

In [3]:
# Create a database (it's just a file!)
print("🏗️ Creating your first database...\n")

# Method 1: Using sqlite3 directly
conn = sqlite3.connect('my_first_database.db')  # Creates a file called my_first_database.db
cursor = conn.cursor()  # A cursor is like a pointer to execute commands

print("✅ Database created!")
print("📁 Check your folder - you'll see 'my_first_database.db'")
print("")
print("🔑 Key Terms:")
print("  - CONNECTION: Your link to the database")
print("  - CURSOR: Executes SQL commands")
print("  - .db FILE: The actual database file")

🏗️ Creating your first database...

✅ Database created!
📁 Check your folder - you'll see 'my_first_database.db'

🔑 Key Terms:
  - CONNECTION: Your link to the database
  - CURSOR: Executes SQL commands
  - .db FILE: The actual database file

### 2.2 Creating Your First Table

In [4]:
# Create a simple table
print("📋 Creating a table is like defining a DataFrame structure:\n")

# Drop table if it exists (for re-running)
cursor.execute("DROP TABLE IF EXISTS students")

# Create table with SQL
create_table_sql = """
CREATE TABLE students (
    student_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    grade REAL,
    enrolled_date DATE
)
"""

cursor.execute(create_table_sql)
conn.commit()  # Save changes

print("SQL Command:")
print(create_table_sql)
print("")
print("✅ Table 'students' created!")
print("")
print("📚 Data Types in SQL:")
print("  - INTEGER: Whole numbers (1, 2, 3)")
print("  - REAL/FLOAT: Decimal numbers (3.14, 2.5)")
print("  - TEXT/VARCHAR: Text strings ('Hello')")
print("  - DATE/DATETIME: Dates and times")
print("  - BOOLEAN: True/False")
print("")
print("🔑 Special Constraints:")
print("  - PRIMARY KEY: Unique identifier for each row")
print("  - NOT NULL: This field cannot be empty")
print("  - UNIQUE: No duplicates allowed")
print("  - DEFAULT: Default value if none provided")

📋 Creating a table is like defining a DataFrame structure:

SQL Command:

CREATE TABLE students (
    student_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    grade REAL,
    enrolled_date DATE
)


✅ Table 'students' created!

📚 Data Types in SQL:
  - INTEGER: Whole numbers (1, 2, 3)
  - REAL/FLOAT: Decimal numbers (3.14, 2.5)
  - TEXT/VARCHAR: Text strings ('Hello')
  - DATE/DATETIME: Dates and times
  - BOOLEAN: True/False

🔑 Special Constraints:
  - PRIMARY KEY: Unique identifier for each row
  - NOT NULL: This field cannot be empty
  - UNIQUE: No duplicates allowed
  - DEFAULT: Default value if none provided

### 2.3 Inserting Data into Tables

In [5]:
# Insert data - Method 1: One row at a time
print("➕ INSERTING DATA\n")
print("Method 1: Insert one row")

insert_sql = """
INSERT INTO students (name, age, grade, enrolled_date)
VALUES ('Alice Smith', 20, 85.5, '2024-01-15')
"""

cursor.execute(insert_sql)
print("SQL:")
print(insert_sql)

# Method 2: Insert multiple rows
print("\nMethod 2: Insert multiple rows")

students_data = [
    ('Bob Johnson', 21, 92.0, '2024-01-15'),
    ('Charlie Brown', 19, 78.5, '2024-01-16'),
    ('Diana Prince', 22, 95.0, '2024-01-16'),
    ('Eve Wilson', 20, 88.0, '2024-01-17')
]

cursor.executemany(
    "INSERT INTO students (name, age, grade, enrolled_date) VALUES (?, ?, ?, ?)",
    students_data
)

conn.commit()  # Don't forget to commit!

print(f"✅ Inserted {len(students_data) + 1} students!")
print("")
print("💡 The '?' are placeholders - this prevents SQL injection attacks!")

➕ INSERTING DATA

Method 1: Insert one row
SQL:

INSERT INTO students (name, age, grade, enrolled_date)
VALUES ('Alice Smith', 20, 85.5, '2024-01-15')


Method 2: Insert multiple rows
✅ Inserted 5 students!

💡 The '?' are placeholders - this prevents SQL injection attacks!

In [66]:
insert_sql = """
INSERT INTO students (name, age, grade, enrolled_date)
VALUES ('Jessica Paes', 35, 90, '2025-09-09')
"""

cursor.execute(insert_sql)
conn.commit()  # Don't forget to commit!
print("SQL:")
print(insert_sql)

SQL:

INSERT INTO students (name, age, grade, enrolled_date)
VALUES ('Jessica Paes', 35, 90, '2025-09-09')

In [67]:
query = """
SELECT * FROM students WHERE enrolled_date > '2024-01-16'
"""

pd.read_sql(query, conn)

   student_id          name  age  grade enrolled_date
0           5    Eve Wilson   20   88.0    2024-01-17
1           6  Jessica Paes   35   90.0    2025-09-09

In [68]:
delete_sql = "DELETE FROM students WHERE student_id IN (12, 13, 14, 20)"
cursor.execute(delete_sql)
conn.commit()

---

## 🔍 Part 3: Your First SQL Queries

Time to ask questions to your database!

### 3.1 SELECT - Getting Data Out

In [6]:
print("🔍 SELECT QUERIES - The Foundation of SQL\n")

# Query 1: Get everything
print("1️⃣ Get all data (SELECT *)")
query1 = "SELECT * FROM students"
result1 = pd.read_sql(query1, conn)
print(f"SQL: {query1}")
print("Result:")
print(result1)
print("\n" + "="*50 + "\n")

# Query 2: Get specific columns
print("2️⃣ Get specific columns")
query2 = "SELECT name, grade FROM students"
result2 = pd.read_sql(query2, conn)
print(f"SQL: {query2}")
print("Result:")
print(result2)
print("\n" + "="*50 + "\n")

# Query 3: Get with conditions (WHERE)
print("3️⃣ Filter with WHERE")
query3 = "SELECT name, grade FROM students WHERE grade > 85"
result3 = pd.read_sql(query3, conn)
print(f"SQL: {query3}")
print("Result:")
print(result3)

print("\n💡 SELECT is like df[columns] in pandas")
print("💡 WHERE is like df[df['column'] > value] in pandas")

🔍 SELECT QUERIES - The Foundation of SQL

1️⃣ Get all data (SELECT *)
SQL: SELECT * FROM students
Result:
   student_id           name  age  grade enrolled_date
0           1    Alice Smith   20   85.5    2024-01-15
1           2    Bob Johnson   21   92.0    2024-01-15
2           3  Charlie Brown   19   78.5    2024-01-16
3           4   Diana Prince   22   95.0    2024-01-16
4           5     Eve Wilson   20   88.0    2024-01-17

==================================================

2️⃣ Get specific columns
SQL: SELECT name, grade FROM students
Result:
            name  grade
0    Alice Smith   85.5
1    Bob Johnson   92.0
2  Charlie Brown   78.5
3   Diana Prince   95.0
4     Eve Wilson   88.0

==================================================

3️⃣ Filter with WHERE
SQL: SELECT name, grade FROM students WHERE grade > 85
Result:
           name  grade
0   Alice Smith   85.5
1   Bob Johnson   92.0
2  Diana Prince   95.0
3    Eve Wilson   88.0

💡 SELECT is like df[columns] in pandas
💡 WHERE is like df[df['column'] > value] in pandas

### 3.2 WHERE Conditions - Filtering Data

In [7]:
print("🎯 WHERE CLAUSE - Your Data Filter\n")

# Different types of conditions
conditions = [
    ("Equals", "WHERE age = 20", "df[df['age'] == 20]"),
    ("Not equals", "WHERE age != 20", "df[df['age'] != 20]"),
    ("Greater than", "WHERE grade > 80", "df[df['grade'] > 80]"),
    ("Less than", "WHERE age < 21", "df[df['age'] < 21]"),
    ("BETWEEN", "WHERE grade BETWEEN 80 AND 90", "df[(df['grade'] >= 80) & (df['grade'] <= 90)]"),
    ("IN list", "WHERE age IN (19, 20, 21)", "df[df['age'].isin([19, 20, 21])]"),
    ("LIKE pattern", "WHERE name LIKE 'A%'", "df[df['name'].str.startswith('A')]"),
    ("AND", "WHERE age > 19 AND grade > 80", "df[(df['age'] > 19) & (df['grade'] > 80)]"),
    ("OR", "WHERE age < 20 OR grade > 90", "df[(df['age'] < 20) | (df['grade'] > 90)]")
]

for condition_name, sql_example, pandas_equivalent in conditions:
    print(f"📌 {condition_name}:")
    print(f"   SQL:    SELECT * FROM students {sql_example}")
    print(f"   Pandas: {pandas_equivalent}")
    print()

# Example with multiple conditions
print("\n🔥 Real Example:")
complex_query = """
SELECT name, age, grade 
FROM students 
WHERE grade > 80 
  AND age <= 21
  AND name LIKE '%e%'
"""
result = pd.read_sql(complex_query, conn)
print("SQL:")
print(complex_query)
print("\nResult:")
print(result)

🎯 WHERE CLAUSE - Your Data Filter

📌 Equals:
   SQL:    SELECT * FROM students WHERE age = 20
   Pandas: df[df['age'] == 20]

📌 Not equals:
   SQL:    SELECT * FROM students WHERE age != 20
   Pandas: df[df['age'] != 20]

📌 Greater than:
   SQL:    SELECT * FROM students WHERE grade > 80
   Pandas: df[df['grade'] > 80]

📌 Less than:
   SQL:    SELECT * FROM students WHERE age < 21
   Pandas: df[df['age'] < 21]

📌 BETWEEN:
   SQL:    SELECT * FROM students WHERE grade BETWEEN 80 AND 90
   Pandas: df[(df['grade'] >= 80) & (df['grade'] <= 90)]

📌 IN list:
   SQL:    SELECT * FROM students WHERE age IN (19, 20, 21)
   Pandas: df[df['age'].isin([19, 20, 21])]

📌 LIKE pattern:
   SQL:    SELECT * FROM students WHERE name LIKE 'A%'
   Pandas: df[df['name'].str.startswith('A')]

📌 AND:
   SQL:    SELECT * FROM students WHERE age > 19 AND grade > 80
   Pandas: df[(df['age'] > 19) & (df['grade'] > 80)]

📌 OR:
   SQL:    SELECT * FROM students WHERE age < 20 OR grade > 90
   Pandas: df[(df['age'] < 20) | (df['grade'] > 90)]


🔥 Real Example:
SQL:

SELECT name, age, grade
FROM students
WHERE grade > 80
  AND age <= 21
  AND name LIKE '%e%'


Result:
          name  age  grade
0  Alice Smith   20   85.5
1   Eve Wilson   20   88.0

### 3.3 ORDER BY - Sorting Results

In [8]:
print("📊 ORDER BY - Sorting Your Results\n")

# Sort by grade (highest first)
print("1️⃣ Sort by grade (descending)")
query1 = """
SELECT name, grade 
FROM students 
ORDER BY grade DESC
"""
result1 = pd.read_sql(query1, conn)
print("SQL:")
print(query1)
print("\nResult:")
print(result1)
print("\nPandas equivalent: df.sort_values('grade', ascending=False)")
print("\n" + "="*50 + "\n")

# Sort by multiple columns
print("2️⃣ Sort by multiple columns")
query2 = """
SELECT name, age, grade 
FROM students 
ORDER BY age ASC, grade DESC
"""
result2 = pd.read_sql(query2, conn)
print("SQL:")
print(query2)
print("\nResult:")
print(result2)
print("\nPandas equivalent: df.sort_values(['age', 'grade'], ascending=[True, False])")

📊 ORDER BY - Sorting Your Results

1️⃣ Sort by grade (descending)
SQL:

SELECT name, grade
FROM students
ORDER BY grade DESC


Result:
            name  grade
0   Diana Prince   95.0
1    Bob Johnson   92.0
2     Eve Wilson   88.0
3    Alice Smith   85.5
4  Charlie Brown   78.5

Pandas equivalent: df.sort_values('grade', ascending=False)

==================================================

2️⃣ Sort by multiple columns
SQL:

SELECT name, age, grade
FROM students
ORDER BY age ASC, grade DESC


Result:
            name  age  grade
0  Charlie Brown   19   78.5
1     Eve Wilson   20   88.0
2    Alice Smith   20   85.5
3    Bob Johnson   21   92.0
4   Diana Prince   22   95.0

Pandas equivalent: df.sort_values(['age', 'grade'], ascending=[True, False])

### 3.4 Aggregate Functions - Summarizing Data

In [9]:
print("📈 AGGREGATE FUNCTIONS - Data Summaries\n")

# Common aggregate functions
aggregates = [
    ("COUNT", "SELECT COUNT(*) as total_students FROM students", "len(df)"),
    ("SUM", "SELECT SUM(grade) as total_grades FROM students", "df['grade'].sum()"),
    ("AVG", "SELECT AVG(grade) as average_grade FROM students", "df['grade'].mean()"),
    ("MAX", "SELECT MAX(grade) as highest_grade FROM students", "df['grade'].max()"),
    ("MIN", "SELECT MIN(age) as youngest_age FROM students", "df['age'].min()")
]

for func_name, sql_query, pandas_equiv in aggregates:
    result = pd.read_sql(sql_query, conn)
    print(f"📊 {func_name}:")
    print(f"   SQL: {sql_query}")
    print(f"   Result: {result.iloc[0, 0]:.2f if func_name in ['AVG', 'SUM'] else result.iloc[0, 0]}")
    print(f"   Pandas: {pandas_equiv}")
    print()

# All together
print("\n🔥 Multiple aggregations:")
summary_query = """
SELECT 
    COUNT(*) as total_students,
    AVG(age) as avg_age,
    AVG(grade) as avg_grade,
    MIN(grade) as min_grade,
    MAX(grade) as max_grade
FROM students
"""
summary = pd.read_sql(summary_query, conn)
print("SQL:")
print(summary_query)
print("\nResult:")
print(summary)

📈 AGGREGATE FUNCTIONS - Data Summaries

📊 COUNT:
   SQL: SELECT COUNT(*) as total_students FROM students

ValueError: Invalid format specifier '.2f if func_name in ['AVG', 'SUM'] else result.iloc[0, 0]' for object of type 'int'

### 3.5 GROUP BY - Grouping Data

In [10]:
print("👥 GROUP BY - Analyzing Groups\n")

# First, let's add a department column for grouping
cursor.execute("ALTER TABLE students ADD COLUMN department TEXT")
departments = ['Engineering', 'Science', 'Arts', 'Engineering', 'Science']
for i, dept in enumerate(departments, 1):
    cursor.execute(f"UPDATE students SET department = '{dept}' WHERE student_id = {i}")
conn.commit()

# Now let's group!
print("Average grade by department:")
group_query = """
SELECT 
    department,
    COUNT(*) as student_count,
    AVG(grade) as avg_grade,
    MAX(grade) as top_grade
FROM students
GROUP BY department
ORDER BY avg_grade DESC
"""

result = pd.read_sql(group_query, conn)
print("SQL:")
print(group_query)
print("\nResult:")
print(result)
print("\nPandas equivalent:")
print("df.groupby('department').agg({")
print("    'grade': ['count', 'mean', 'max']")
print("})")

👥 GROUP BY - Analyzing Groups

Average grade by department:
SQL:

SELECT
    department,
    COUNT(*) as student_count,
    AVG(grade) as avg_grade,
    MAX(grade) as top_grade
FROM students
GROUP BY department
ORDER BY avg_grade DESC


Result:
    department  student_count  avg_grade  top_grade
0  Engineering              2      90.25       95.0
1      Science              2      90.00       92.0
2         Arts              1      78.50       78.5

Pandas equivalent:
df.groupby('department').agg({
    'grade': ['count', 'mean', 'max']
})

---

## 🔄 Part 4: Converting Between Pandas and SQL

The real power comes from seamlessly moving between pandas and SQL!

### 4.1 DataFrame to SQL Database

In [11]:
print("🔄 CONVERTING PANDAS TO SQL\n")

# Create a sample DataFrame
sales_data = pd.DataFrame({
    'date': pd.date_range('2024-01-01', periods=30, freq='D'),
    'product': np.random.choice(['Laptop', 'Phone', 'Tablet'], 30),
    'quantity': np.random.randint(1, 10, 30),
    'price': np.random.uniform(100, 1000, 30).round(2),
    'customer_id': np.random.randint(1, 10, 30)
})

# Calculate revenue
sales_data['revenue'] = sales_data['quantity'] * sales_data['price']

print("📊 Original DataFrame:")
print(sales_data.head())
print(f"\nShape: {sales_data.shape}")

# Save to SQL database
print("\n💾 Saving to SQL...")
sales_data.to_sql(
    name='sales',           # Table name
    con=conn,               # Database connection
    if_exists='replace',    # Replace if table exists
    index=False            # Don't save the index
)

print("✅ DataFrame saved to SQL!")

# Verify it worked
verify_query = "SELECT COUNT(*) as row_count FROM sales"
result = pd.read_sql(verify_query, conn)
print(f"\n🔍 Verification: {result.iloc[0, 0]} rows in SQL table")

print("\n📝 Key Parameters for to_sql():")
print("  - name: Table name in database")
print("  - con: Database connection")
print("  - if_exists: 'fail', 'replace', or 'append'")
print("  - index: Save DataFrame index as column?")
print("  - dtype: Specify SQL data types")
print("  - method: How to insert (default is best)")

🔄 CONVERTING PANDAS TO SQL

📊 Original DataFrame:
        date product  quantity   price  customer_id  revenue
0 2024-01-01  Laptop         7  117.10            6   819.70
1 2024-01-02   Phone         4  353.00            9  1412.00
2 2024-01-03  Laptop         1  264.94            4   264.94
3 2024-01-04  Tablet         7  526.31            6  3684.17
4 2024-01-05  Laptop         5  904.19            9  4520.95

Shape: (30, 6)

💾 Saving to SQL...
✅ DataFrame saved to SQL!

🔍 Verification: 30 rows in SQL table

📝 Key Parameters for to_sql():
  - name: Table name in database
  - con: Database connection
  - if_exists: 'fail', 'replace', or 'append'
  - index: Save DataFrame index as column?
  - dtype: Specify SQL data types
  - method: How to insert (default is best)

### 4.2 SQL Query Results to DataFrame

In [12]:
print("📥 READING SQL INTO PANDAS\n")

# Method 1: Simple query
print("1️⃣ Simple Query:")
query = "SELECT * FROM sales WHERE quantity > 5"
df1 = pd.read_sql(query, conn)
print(f"Query: {query}")
print(f"Result shape: {df1.shape}")
print(df1.head())

print("\n" + "="*50 + "\n")

# Method 2: Complex query with aggregation
print("2️⃣ Complex Query:")
complex_query = """
SELECT 
    product,
    COUNT(*) as total_sales,
    SUM(quantity) as total_quantity,
    AVG(price) as avg_price,
    SUM(revenue) as total_revenue
FROM sales
GROUP BY product
ORDER BY total_revenue DESC
"""

df2 = pd.read_sql(complex_query, conn)
print("Query: [Complex aggregation query]")
print("\nResult:")
print(df2)

# Now we can use pandas operations on the result!
print("\n🎯 Now we can use pandas on the SQL results:")
print(f"Most profitable product: {df2.iloc[0]['product']}")
print(f"Total revenue across all products: ${df2['total_revenue'].sum():,.2f}")

📥 READING SQL INTO PANDAS

1️⃣ Simple Query:
Query: SELECT * FROM sales WHERE quantity > 5
Result shape: (15, 6)
                  date product  quantity   price  customer_id  revenue
0  2024-01-01 00:00:00  Laptop         7  117.10            6   819.70
1  2024-01-04 00:00:00  Tablet         7  526.31            6  3684.17
2  2024-01-06 00:00:00   Phone         9  409.34            7  3684.06
3  2024-01-08 00:00:00  Laptop         9  899.01            1  8091.09
4  2024-01-09 00:00:00  Laptop         7  304.30            2  2130.10

==================================================

2️⃣ Complex Query:
Query: [Complex aggregation query]

Result:
  product  total_sales  total_quantity   avg_price  total_revenue
0  Laptop           13              65  585.073077       37513.73
1   Phone           10              66  565.227000       37460.74
2  Tablet            7              34  626.731429       20815.84

🎯 Now we can use pandas on the SQL results:
Most profitable product: Laptop
Total revenue across all products: $95,790.31

### 4.3 Updating and Deleting Data

In [13]:
print("✏️ UPDATING DATA IN SQL\n")

# UPDATE: Change existing data
print("Before update:")
before = pd.read_sql("SELECT * FROM students WHERE student_id = 1", conn)
print(before)

# Update grade
update_sql = """
UPDATE students 
SET grade = 90.0 
WHERE student_id = 1
"""
cursor.execute(update_sql)
conn.commit()

print("\nAfter update:")
after = pd.read_sql("SELECT * FROM students WHERE student_id = 1", conn)
print(after)

print("\n" + "="*50 + "\n")

# DELETE: Remove data
print("🗑️ DELETING DATA\n")

# Count before
before_count = pd.read_sql("SELECT COUNT(*) as count FROM sales", conn).iloc[0, 0]
print(f"Records before delete: {before_count}")

# Delete records with low quantity
delete_sql = "DELETE FROM sales WHERE quantity = 1"
cursor.execute(delete_sql)
conn.commit()

# Count after
after_count = pd.read_sql("SELECT COUNT(*) as count FROM sales", conn).iloc[0, 0]
print(f"Records after delete: {after_count}")
print(f"Deleted {before_count - after_count} records")

print("\n⚠️ WARNING: DELETE is permanent! Always backup important data!")

✏️ UPDATING DATA IN SQL

Before update:
   student_id         name  age  grade enrolled_date   department
0           1  Alice Smith   20   85.5    2024-01-15  Engineering

After update:
   student_id         name  age  grade enrolled_date   department
0           1  Alice Smith   20   90.0    2024-01-15  Engineering

==================================================

🗑️ DELETING DATA

Records before delete: 30
Records after delete: 27
Deleted 3 records

⚠️ WARNING: DELETE is permanent! Always backup important data!

---

## 🚀 Part 5: Essential SQL Patterns for Data Science

Let's learn the SQL patterns you'll use every day as a data scientist!

### 5.1 JOIN - Combining Tables

In [14]:
print("🔗 JOINS - Combining Multiple Tables\n")

# Create related tables
# Customers table
customers_df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'city': ['NYC', 'LA', 'Chicago', 'NYC', 'Boston']
})

# Orders table
orders_df = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105],
    'customer_id': [1, 2, 1, 3, 1],
    'product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Mouse'],
    'amount': [1000, 800, 500, 1200, 50]
})

# Save to database
customers_df.to_sql('customers_table', conn, if_exists='replace', index=False)
orders_df.to_sql('orders_table', conn, if_exists='replace', index=False)

print("📊 Customers:")
print(customers_df)
print("\n📊 Orders:")
print(orders_df)

print("\n" + "="*50 + "\n")

# JOIN them together
join_query = """
SELECT 
    c.name,
    c.city,
    o.product,
    o.amount
FROM customers_table c
JOIN orders_table o ON c.customer_id = o.customer_id
ORDER BY c.name
"""

print("🔗 JOINED Result:")
print("SQL:")
print(join_query)
print("\nResult:")
joined = pd.read_sql(join_query, conn)
print(joined)

print("\n💡 This is like pd.merge(customers, orders, on='customer_id') in pandas!")

🔗 JOINS - Combining Multiple Tables

📊 Customers:
   customer_id     name     city
0            1    Alice      NYC
1            2      Bob       LA
2            3  Charlie  Chicago
3            4    Diana      NYC
4            5      Eve   Boston

📊 Orders:
   order_id  customer_id product  amount
0       101            1  Laptop    1000
1       102            2   Phone     800
2       103            1  Tablet     500
3       104            3  Laptop    1200
4       105            1   Mouse      50

==================================================

🔗 JOINED Result:
SQL:

SELECT
    c.name,
    c.city,
    o.product,
    o.amount
FROM customers_table c
JOIN orders_table o ON c.customer_id = o.customer_id
ORDER BY c.name


Result:
      name     city product  amount
0    Alice      NYC  Laptop    1000
1    Alice      NYC   Mouse      50
2    Alice      NYC  Tablet     500
3      Bob       LA   Phone     800
4  Charlie  Chicago  Laptop    1200

💡 This is like pd.merge(customers, orders, on='customer_id') in pandas!

### 5.2 Common Data Science Queries

In [15]:
print("📊 COMMON DATA SCIENCE SQL PATTERNS\n")

# Pattern 1: Find duplicates
print("1️⃣ Finding Duplicates:")
duplicate_query = """
SELECT 
    product,
    COUNT(*) as count
FROM sales
GROUP BY product
HAVING COUNT(*) > 5
"""
print(f"SQL: {duplicate_query}")
duplicates = pd.read_sql(duplicate_query, conn)
print("Products appearing more than 5 times:")
print(duplicates)

print("\n" + "="*50 + "\n")

# Pattern 2: Date filtering
print("2️⃣ Date Range Filtering:")
date_query = """
SELECT 
    DATE(date) as sale_date,
    SUM(revenue) as daily_revenue
FROM sales
WHERE date BETWEEN '2024-01-01' AND '2024-01-07'
GROUP BY DATE(date)
ORDER BY sale_date
"""
print(f"SQL: [Date range query]")
date_results = pd.read_sql(date_query, conn)
print("First week revenue:")
print(date_results.head())

print("\n" + "="*50 + "\n")

# Pattern 3: Top N per category
print("3️⃣ Top N per Category:")
top_n_query = """
SELECT * FROM (
    SELECT 
        product,
        date,
        revenue,
        ROW_NUMBER() OVER (PARTITION BY product ORDER BY revenue DESC) as rank
    FROM sales
) ranked
WHERE rank <= 3
"""
print("Get top 3 sales for each product")
print("(This uses window functions - advanced SQL!)")

📊 COMMON DATA SCIENCE SQL PATTERNS

1️⃣ Finding Duplicates:
SQL:
SELECT
    product,
    COUNT(*) as count
FROM sales
GROUP BY product
HAVING COUNT(*) > 5

Products appearing more than 5 times:
  product  count
0  Laptop     10
1   Phone     10
2  Tablet      7

==================================================

2️⃣ Date Range Filtering:
SQL: [Date range query]
First week revenue:
    sale_date  daily_revenue
0  2024-01-01         819.70
1  2024-01-02        1412.00
2  2024-01-04        3684.17
3  2024-01-05        4520.95
4  2024-01-06        3684.06

==================================================

3️⃣ Top N per Category:
Get top 3 sales for each product
(This uses window functions - advanced SQL!)

---

## 💪 Part 6: Practice Exercises

Time to test your SQL skills!

### Exercise 1: Basic Queries

In [16]:
print("📝 EXERCISE 1: Write these queries\n")

print("1. Get all students with grade above 90")
exercise_1 = "SELECT * FROM students WHERE grade > 90"
pd.read_sql(exercise_1, conn)

print("2. Count how many sales were made for each product")
exercise_2 = "SELECT product, COUNT(*) as sales_count FROM sales GROUP BY product"
print(exercise_2)
print("")
pd.read_sql(exercise_2, conn)

print("3. Find the average price for products sold in quantities > 5")
exercise_3 = "SELECT AVG(price) as average_price, product FROM sales WHERE quantity > 5"
print(exercise_3)
print("")
pd.read_sql(exercise_3, conn)

# Solutions (uncomment to see)
"""
Solution 1:
solution1 = "SELECT * FROM students WHERE grade > 90"

Solution 2:
solution2 = "SELECT product, COUNT(*) as sales_count FROM sales GROUP BY product"

Solution 3:
solution3 = "SELECT AVG(price) as avg_price FROM sales WHERE quantity > 5"
"""

📝 EXERCISE 1: Write these queries

1. Get all students with grade above 90
2. Count how many sales were made for each product
SELECT product, COUNT(*) as sales_count FROM sales GROUP BY product

3. Find the average price for products sold in quantities > 5
SELECT AVG(price) as average_price, product FROM sales WHERE quantity > 5

'\nSolution 1:\nsolution1 = "SELECT * FROM students WHERE grade > 90"\n\nSolution 2:\nsolution2 = "SELECT product, COUNT(*) as sales_count FROM sales GROUP BY product"\n\nSolution 3:\nsolution3 = "SELECT AVG(price) as avg_price FROM sales WHERE quantity > 5"\n'

In [ ]:
print("1. Get all students with grade above 90")
exercise_1 = "SELECT * FROM students WHERE grade > 90"
print(exercise_1)
print("")
pd.read_sql(exercise_1, conn)

1. Get all students with grade above 90
SELECT * FROM students WHERE grade > 90

   student_id          name  age  grade enrolled_date   department
0           2   Bob Johnson   21   92.0    2024-01-15      Science
1           4  Diana Prince   22   95.0    2024-01-16  Engineering
2           7   Bob Johnson   21   92.0    2024-01-15         None
3           9  Diana Prince   22   95.0    2024-01-16         None
4          16   Bob Johnson   21   92.0    2024-01-15         None
5          18  Diana Prince   22   95.0    2024-01-16         None

In [ ]:
print("2. Count how many sales were made for each product")
exercise_2 = "SELECT product, COUNT(*) as sales_count FROM sales GROUP BY product"
print(exercise_2)
print("")
pd.read_sql(exercise_2, conn)

2. Count how many sales were made for each product
SELECT product, COUNT(*) as sales_count FROM sales GROUP BY product

  product  sales_count
0  Laptop            9
1   Phone            8
2  Tablet           13

In [ ]:
print("3. Find the average price for products sold in quantities > 5")
exercise_3 = "SELECT AVG(price) as average_price, product FROM sales WHERE quantity > 5"
print(exercise_3)
print("")
pd.read_sql(exercise_3, conn)

3. Find the average price for products sold in quantities > 5
SELECT AVG(price) as average_price, product FROM sales WHERE quantity > 5

   average_price product
0     587.798235  Tablet

### Exercise 2: Create Your Own Database

In [18]:
print("🏗️ EXERCISE 2: Create a Movie Database\n")

print("Your task:")
print("1. Create a 'movies' table with columns:")
print("   - movie_id (INTEGER PRIMARY KEY)")
print("   - title (TEXT)")
print("   - year (INTEGER)")
print("   - rating (REAL)")
print("")
print("2. Insert at least 3 movies")
print("")
print("3. Query to find movies with rating > 8.0")
print("")

# Your code here:
conn_movies = sqlite3.connect('movies.db')
cursor_movies = conn_movies.cursor()

# 1. Create the movies table
create_table_sql = """
CREATE TABLE IF NOT EXISTS movies (
    movie_id INTEGER PRIMARY KEY,
    title TEXT,
    year INTEGER,
    rating REAL
)
"""
cursor_movies.execute(create_table_sql)
conn_movies.commit()

# 2. Insert at least 3 movies
movies_data = [
    (1, 'The Shawshank Redemption', 1994, 9.3),
    (2, 'The Godfather', 1972, 9.2),
    (3, 'The Dark Knight', 2008, 9.0),
    (4, 'Pulp Fiction', 1994, 8.9),
    (5, 'Inception', 2010, 8.8)
]

insert_sql = "INSERT OR REPLACE INTO movies VALUES (?, ?, ?, ?)"
cursor_movies.executemany(insert_sql, movies_data)
conn_movies.commit()

# 3. Query to find movies with rating > 8.0
query_sql = "SELECT * FROM movies WHERE rating > 8.0"
cursor_movies.execute(query_sql)
high_rated_movies = cursor_movies.fetchall()

print("Movies with rating > 8.0:")
for movie in high_rated_movies:
    print(f"ID: {movie[0]}, Title: {movie[1]}, Year: {movie[2]}, Rating: {movie[3]}")

# Close connection
conn_movies.close()

🏗️ EXERCISE 2: Create a Movie Database

Your task:
1. Create a 'movies' table with columns:
   - movie_id (INTEGER PRIMARY KEY)
   - title (TEXT)
   - year (INTEGER)
   - rating (REAL)

2. Insert at least 3 movies

3. Query to find movies with rating > 8.0

Movies with rating > 8.0:
ID: 1, Title: The Shawshank Redemption, Year: 1994, Rating: 9.3
ID: 2, Title: The Godfather, Year: 1972, Rating: 9.2
ID: 3, Title: The Dark Knight, Year: 2008, Rating: 9.0
ID: 4, Title: Pulp Fiction, Year: 1994, Rating: 8.9
ID: 5, Title: Inception, Year: 2010, Rating: 8.8
ID: 9, Title: Top Gun: Maverick, Year: 2022, Rating: 8.3
ID: 10, Title: Spider-Man: No Way Home, Year: 2021, Rating: 8.2
ID: 11, Title: Inside Out, Year: 2015, Rating: 8.1
ID: 14, Title: Harry Potter and the Deathly Hallows – Part 2, Year: 2011, Rating: 8.1

---

## 🎯 SQL Cheat Sheet

Keep this handy!

In [20]:
print("📋 SQL CHEAT SHEET\n")

cheat_sheet = """
🔍 BASIC QUERIES:
SELECT * FROM table                          -- Get everything
SELECT col1, col2 FROM table                 -- Get specific columns
SELECT DISTINCT col FROM table               -- Unique values only
SELECT * FROM table LIMIT 10                 -- First 10 rows

🎯 FILTERING:
WHERE col = 'value'                          -- Exact match
WHERE col != 'value'                         -- Not equal
WHERE col > 100                              -- Greater than
WHERE col BETWEEN 10 AND 20                  -- Range
WHERE col IN ('A', 'B', 'C')                -- In list
WHERE col LIKE 'A%'                          -- Starts with A
WHERE col IS NULL                            -- Null values
WHERE col IS NOT NULL                        -- Non-null values

📊 AGGREGATION:
COUNT(*)                                      -- Count rows
COUNT(DISTINCT col)                          -- Count unique
SUM(col)                                      -- Sum values
AVG(col)                                      -- Average
MAX(col) / MIN(col)                          -- Max/Min

👥 GROUPING:
GROUP BY col                                  -- Group rows
HAVING COUNT(*) > 5                          -- Filter groups

📈 SORTING:
ORDER BY col ASC                             -- Sort ascending
ORDER BY col DESC                            -- Sort descending
ORDER BY col1, col2                          -- Multiple columns

🔗 JOINING:
JOIN table2 ON table1.col = table2.col       -- Inner join
LEFT JOIN table2 ON ...                      -- Keep all from left
RIGHT JOIN table2 ON ...                     -- Keep all from right

✏️ MODIFYING DATA:
INSERT INTO table (col1, col2) VALUES (?, ?) -- Insert data
UPDATE table SET col = value WHERE ...       -- Update data
DELETE FROM table WHERE ...                  -- Delete rows

🏗️ TABLE OPERATIONS:
CREATE TABLE name (...)                      -- Create table
DROP TABLE name                              -- Delete table
ALTER TABLE name ADD COLUMN col TYPE         -- Add column
"""

print(cheat_sheet)

📋 SQL CHEAT SHEET


🔍 BASIC QUERIES:
SELECT * FROM table                          -- Get everything
SELECT col1, col2 FROM table                 -- Get specific columns
SELECT DISTINCT col FROM table               -- Unique values only
SELECT * FROM table LIMIT 10                 -- First 10 rows

🎯 FILTERING:
WHERE col = 'value'                          -- Exact match
WHERE col != 'value'                         -- Not equal
WHERE col > 100                              -- Greater than
WHERE col BETWEEN 10 AND 20                  -- Range
WHERE col IN ('A', 'B', 'C')                -- In list
WHERE col LIKE 'A%'                          -- Starts with A
WHERE col IS NULL                            -- Null values
WHERE col IS NOT NULL                        -- Non-null values

📊 AGGREGATION:
COUNT(*)                                      -- Count rows
COUNT(DISTINCT col)                          -- Count unique
SUM(col)                                      -- Sum values
AVG(col)                                      -- Average
MAX(col) / MIN(col)                          -- Max/Min

👥 GROUPING:
GROUP BY col                                  -- Group rows
HAVING COUNT(*) > 5                          -- Filter groups

📈 SORTING:
ORDER BY col ASC                             -- Sort ascending
ORDER BY col DESC                            -- Sort descending
ORDER BY col1, col2                          -- Multiple columns

🔗 JOINING:
JOIN table2 ON table1.col = table2.col       -- Inner join
LEFT JOIN table2 ON ...                      -- Keep all from left
RIGHT JOIN table2 ON ...                     -- Keep all from right

✏️ MODIFYING DATA:
INSERT INTO table (col1, col2) VALUES (?, ?) -- Insert data
UPDATE table SET col = value WHERE ...       -- Update data
DELETE FROM table WHERE ...                  -- Delete rows

🏗️ TABLE OPERATIONS:
CREATE TABLE name (...)                      -- Create table
DROP TABLE name                              -- Delete table
ALTER TABLE name ADD COLUMN col TYPE         -- Add column

---

## 🎓 Key Takeaways

Congratulations! You now know SQL fundamentals! Here's what you learned:

1. **What SQL Is**: A language for talking to databases
2. **Why SQL Matters**: Handle data too big for pandas
3. **Basic Operations**: SELECT, WHERE, ORDER BY, GROUP BY
4. **Pandas Integration**: Seamlessly convert between DataFrames and SQL
5. **CRUD Operations**: Create, Read, Update, Delete
6. **Joins**: Combine multiple tables
7. **Best Practices**: Use parameters to prevent SQL injection

---

## 🚀 Next Steps

You're ready to:
1. Work with the other SQL notebooks (01-04)
2. Query real databases
3. Build data pipelines
4. Ace SQL interview questions

**Remember**: SQL + Pandas = Data Science Superpower! 💪

In [21]:
# Cleanup
conn.close()
print("✅ Database connection closed.")
print("🎉 Congratulations! You now know SQL basics!")
print("")
print("📚 Next: Try the practice exercises, then move to notebook 01!")

✅ Database connection closed.
🎉 Congratulations! You now know SQL basics!

📚 Next: Try the practice exercises, then move to notebook 01!